"""empty message

Revision ID: 7af553b01fc0
Revises: 9ac25aae73a1
Create Date: 2024-02-20 12:22:02.774246

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7af553b01fc0'
down_revision = '9ac25aae73a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
