"""empty message

Revision ID: f154de2f2271
Revises: 533274299a85
Create Date: 2024-02-20 11:32:30.576361

"""
import sqlalchemy as sa
from alembic import op

'''
(myproject) c:\projects\myproject>flask db migrate

(myproject) c:\projects\myproject>flask db upgrade
sqlite3.IntegrityError: NOT NULL constraint failed: _alembic_tmp_question.user_id
'''

# revision identifiers, used by Alembic.
revision = 'f154de2f2271'
down_revision = '533274299a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
